MallocNanoZone=0
USER=jorgeolayo
COMMAND_MODE=unix2003
__CFBundleIdentifier=com.microsoft.VSCode
PATH=/Library/Frameworks/Python.framework/Versions/3.13/bin:/opt/homebrew/opt/tcl-tk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Frameworks/Python.framework/Versions/3.13/bin:/opt/homebrew/opt/tcl-tk/bin:/Users/jorgeolayo/.vscode/extensions/ms-python.debugpy-2025.8.0-darwin-arm64/bundled/scripts/noConfigScripts:/Users/jorgeolayo/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand
LOGNAME=jorgeolayo
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.19WpYZALIS/Listeners
HOME=/Users/jorgeolayo
SHELL=/bin/zsh
TMPDIR=/var/folders/92/jp0f3kvd0d1_7q2x10flkwlm0000gn/T/
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
XPC_SERVICE_NAME=0
XPC_FLAGS=0x0
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
SHLVL=1
PWD=/Users/jorgeolayo/Documents/VScode/llama-green-audit
OLDPWD=/Users/jorgeolayo/Documents/VScode/llama-green-audit
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
INFOPATH=/opt/homebrew/share/info:/opt/homebrew/share/info:
LDFLAGS=-L/opt/homebrew/opt/tcl-tk/lib
CPPFLAGS=-I/opt/homebrew/opt/tcl-tk/include
PKG_CONFIG_PATH=/opt/homebrew/opt/tcl-tk/lib/pkgconfig
TK_SILENCE_DEPRECATION=1
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.100.1
LANG=en_US.UTF-8
COLORTERM=truecolor
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/var/folders/92/jp0f3kvd0d1_7q2x10flkwlm0000gn/T/vscode-git-39cc9b3e95.sock
PYDEVD_DISABLE_FILE_VALIDATION=1
VSCODE_DEBUGPY_ADAPTER_ENDPOINTS=/Users/jorgeolayo/.vscode/extensions/ms-python.debugpy-2025.8.0-darwin-arm64/.noConfigDebugAdapterEndpoints/endpoint-674ba41a851cedbf.txt
BUNDLED_DEBUGPY_PATH=/Users/jorgeolayo/.vscode/extensions/ms-python.debugpy-2025.8.0-darwin-arm64/bundled/libs/debugpy
VSCODE_INJECTION=1
ZDOTDIR=/Users/jorgeolayo
USER_ZDOTDIR=/Users/jorgeolayo
TERM=xterm-256color
VSCODE_PROFILE_INITIALIZED=1
VSCODE_LOGIN_INITIALIZED=1
_=/usr/local/bin/python3
